use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Represents a blog post returned by the `/posts` API.
///
/// This structure includes a unique identifier, metadata, and content.
/// It is used both internally and in JSON responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Post {
    /// Unique identifier for the post (e.g., UUID).
    pub id: String,

    /// Name of the person who authored the post.
    pub author: String,

    /// UTC timestamp indicating when the post was created or last updated.
    pub date: DateTime<Utc>,

    /// Main content body of the post.
    pub content: String,
}

/// Input structure used to create or update a blog post via API requests.
///
/// This struct excludes the `id` field, which is generated by the server.
/// It is used in `POST /posts` and `PUT /posts/{id}` requests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostInput {
    /// Name of the post's author.
    pub author: String,

    /// UTC timestamp for the post (typically the authored time).
    pub date: DateTime<Utc>,

    /// Content to be stored in the post.
    pub content: String,
}
